spring:
  redis:
    host: 127.0.0.1
    password: 123456789
    database: 2
    port: 6379
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0
    timeout: 3000

